"""Add simple role system for production

Revision ID: 9a81297418b4
Revises: abef4c73b742
Create Date: 2025-07-16 17:57:47.280261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a81297418b4'
down_revision = 'abef4c73b742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Solo agregar lo mínimo necesario para el sistema de roles
    
    # 1. Agregar columna 'role' a la tabla user
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
    
    # 2. Agregar campos opcionales a equipo (útiles pero no críticos)
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=True))
    
    # 3. Crear tabla simple de asignaciones user_equipos
    op.create_table('user_equipos',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('equipo_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['equipo_id'], ['equipo.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('user_id', 'equipo_id')
    )
    
    # 4. Establecer valores por defecto
    op.execute("UPDATE user SET role = 'user' WHERE role IS NULL")
    op.execute("UPDATE equipo SET estado = 'desconocido' WHERE estado IS NULL")
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Eliminar todo lo agregado
    op.drop_table('user_equipos')
    
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_column('estado')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('descripcion')
    
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')
    # ### end Alembic commands ###
